name: appointment_doctor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  get_storage: ^2.1.1
  get: ^4.6.6
  cloud_firestore: ^4.17.2
  intl: ^0.19.0
  top_snackbar_flutter: ^3.1.0
  image_picker: ^0.8.4+2
  google_maps_flutter: ^2.6.1
  flutter_inner_drawer: ^1.0.0+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
  assets:
<<<<<<< HEAD
    - assets/images/
=======
    - assets/images/gambar.png
    - assets/images/hospify.png
    - assets/images/menu1.png
    - assets/images/menu2.png
    - assets/images/rs.png
    - assets/images/dokter.png
    - assets/images/bgrs.png
    - assets/images/doctor1.png
    - assets/images/doctor2.png
    - assets/images/doctor3.png
    - assets/images/doctor4.png
    - assets/images/doctor5.png
    - assets/images/kulit.png
    - assets/images/anak.png
    - assets/images/dokter_umum.png
    - assets/images/penyakit_dalam.png
    - assets/images/psikologi_klinis.png
    - assets/images/covid19.png
    - assets/images/gizi_klinik.png
    - assets/images/kandungan.png
    - assets/images/hewan.png
    - assets/images/tht.png
    - assets/images/konsultasi.png
    - assets/images/gigi.png
    - assets/images/psikiater.png
    - assets/images/seksologi.png
    - assets/images/bedah.png
    - assets/images/saraf.png
    - assets/images/jantung.png
    - assets/images/laktasi.png
    - assets/images/program_hamil.png
    - assets/images/mata.png
    - assets/images/paru.png
    - assets/images/fisioterapi.png
    - assets/images/medikolegal.png
    - assets/images/talk_therapy.png
    - assets/images/pemeriksaan_lab.png
    - assets/images/bidanku.png
    - assets/images/layanan_kontrasepsi.png
    - assets/images/temuidokter.png
    - assets/images/chatdokter.png
    - assets/images/menuspesialis.png
>>>>>>> 09b5d88247991e31baec0b6f332d04b9da0d06e6
