name: appointment_doctor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  get_storage: ^2.1.1
  get: ^4.6.6
  cloud_firestore: ^4.17.2
  intl: ^0.19.0
  top_snackbar_flutter: ^3.1.0
  image_picker: ^0.8.4+2
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  geoflutterfire2: ^2.3.15
  flutter_inner_drawer: ^1.0.0+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
  assets:
    - assets/images/